### PR TITLE
Add nanoseconds to temporary filename

### PR DESCRIPTION
**Pull request by PabRod**
## Description

This minimal change avoids malfunctions if two or more calls to `force-level1-csd` happen in the very same second.

The change...
- ... adds extra information without removing anything →  is backwards compatible
- ... only affects the name of a temporary folder → has no permanent side effects
- ... will still fail if the calls happen in the same nanosecond, but the chances are a thousand-millionth lower 🤓

## Context

I found this problem when parallelizing the download of `level1` data using `force-level1-csd`. Specifically, I split the time intervals in, for instance, 4 subintervals, and afterward process each subinterval in a different core. I needed this _"hack"_ to make it work.

## Other

I am very interested in knowing if the authors recommend a better way of parallelizing this step.

All the best.

### CODE REVIEW

**Comment by ernstste** [comment]
Hi Pablo,

Thanks for your suggestion.
Force-level1-csd downloads are already running in parallel. Did you find any improvements when running several instances of force-level1-csd?

Stefan

**Comment by PabRod** [comment]
Dear @ernstste, thanks for your quick response.

I am intrigued by the possibilities of parallelization of `force-level1-csd`. I didn't see any reference to parallelization in [the documentation about level 1](https://force-eo.readthedocs.io/en/latest/howto/level1-csd.html). This contrasts strongly with the parallelization for level 2, which is [described in detail](https://force-eo.readthedocs.io/en/latest/howto/l2-ard.html#parallel-processing). Certainly I am missing something. Any help/reference will be very welcome.

#### Answer to your question

My colleagues reported an increase in speed when trying the _split-in-time and parallelize_ approach. I have to say that they tried it manually (basically, launching a bunch of processes manually), and then asked me to automate the process. 

My plan is to do some code profiling/timing to quantify this improvement in a more systematic way. I'll go back to you as soon as possible.

**Comment by ernstste** [comment]
Thank you Pablo.

Force-level1-csd uses gsutil to handle the communication with Google servers and downloads are running in parallel by default. 
If you would like to tweak the number of cores and threads, you can do so by editing the gsutil configuration file (called '.boto' in your home directory). You can find the official documentation for gsutil [here](https://cloud.google.com/storage/docs/boto-gsutil).

Making use of the parallelization settings for gsutil rather than spawning force-level1-csd processes in parallel seems like the cleaner option to me. Running several instances of force-level1-csd leads to redundant spatial queries for AOIs (which causes the issue with the temp folder) and querying the metadata catalogues (several GB in size) multiple times.

However, if there still are use cases where running the module in parallel is necessary, the slight change of folder names would be ok with me.

**Comment by PabRod** [comment]
Thanks a lot for your quick and useful answer.

**Comment by davidfrantz** [comment]
Hi both,

I can see some advantages of allowing both parallelization strategies, especially if we are in a multi-user or cluster-setup.

I think adding the nanoseconds does not really hurt, thus if it helps for some applications, let's do this.
I am now pulling this request into the ``develop`` branch. Thanks for your contribution @PabRod !

@PabRod, I would be very interested to see your benchmark results!

Cheers,
David

**Comment by PabRod** [comment]
Thank you, @davidfrantz.

I made a quick test. As you can see in the figure below, although there is an improvement in the speed, it is not massive.

times

The figure shows the times it took to get the same level 1 data by:

1. Splitting the desired date range in 1, 2, 3 or 4 approximately equal subintervals.
2. Processing each one in a different core with `force-level1-csd -d <datesubrange> [<other parameters>]`

All the best, and thanks again for your time.

**Pull request merged**
